/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_console_blackjack;

public class App {

    public static void main(String[] args) {

        // Top Banner JSGarvey's Blackjack
        Shell.topGUI();
        Shell.bet();

        // Blank Lines
        for (int i = 0; i < 6; i++)
            System.out.println();

        // Bottom banner
        Shell.bottomGUI();
    }
}
